name: sighas-api
services:
  rdbms:
    image: postgres:17.6
    container_name: sighas-database
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
      POSTGRES_DB: ${DB_NAME:-sighas}
    ports:
      - '5432:5432'
    volumes:
      - type: volume
        source: sighas-database-volume
        target: /var/lib/postgresql/data
    networks:
      - sighas-network
  app:
    build: .
    container_name: sighas-api
    depends_on:
      - rdbms
    environment:
      DB_HOST: rdbms
      DB_NAME: sighas
      DB_USERNAME: admin
      DB_PASSWORD: admin
    ports:
      - '8080:8080'
    networks:
      - sighas-network
volumes:
  sighas-database-volume:

networks:
  sighas-network:
    driver: bridge