apiVersion: v1
kind: Secret
metadata:
  name: {{ include "saga-chart.fullname" . }}-db-secret
  labels:
    {{- include "saga-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
data:
  username: {{ .Values.database.username | b64enc | quote }}
  password: {{ .Values.database.password | b64enc | quote }}
