apiVersion: v1
kind: Service
metadata:
  name: {{ include "saga-chart.fullname" . }}-app
  labels:
    {{- include "saga-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: application
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "saga-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: application
