apiVersion: v2
name: saga-chart
description: Um chart Helm para Kubernetes

# Um chart pode ser um chart de 'aplicação' ou de 'biblioteca'.
#
# Charts de aplicação são uma coleção de templates que podem ser empacotados em arquivos versionados
# para serem implantados.
#
# Charts de biblioteca fornecem utilitários ou funções úteis para o desenvolvedor do chart. Eles são incluídos como
# uma dependência de charts de aplicação para injetar esses utilitários e funções no pipeline de
# renderização. Charts de biblioteca não definem nenhum template e, portanto, não podem ser implantados.
type: application

# Esta é a versão do chart. Este número de versão deve ser incrementado toda vez que você fizer alterações
# no chart e seus templates, incluindo a versão do app.
# As versões devem seguir o Semantic Versioning (https://semver.org/)
version: 0.1.0

# Este é o número de versão da aplicação sendo implantada. Este número de versão deve ser
# incrementado toda vez que você fizer alterações na aplicação. As versões não precisam
# seguir o Semantic Versioning. Elas devem refletir a versão que a aplicação está usando.
# É recomendado usar com aspas.
appVersion: "1.16.0"
