# Configuração do Ambiente de Desenvolvimento
# Este arquivo sobrescreve apenas os valores que diferem do values.yaml padrão

app:
  replicaCount: 1
  springProfile: "dev"
  debug: true
  
  image:
    pullPolicy: Always
    tag: "develop-f3d20b0"
  
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

# Configuração do banco de dados para Desenvolvimento
database:
  clusterName: "saga-chart-dev-postgres"
  host: "saga-chart-dev-postgres-rw"
  name: "sighas_dev"
  password: "admin123"

# Configuração do Job de Migration
migration:
  image:
    tag: "develop-f3d20b0"

# Configuração do Rollout para Dev (BlueGreen)
rollout:
  strategy: "blueGreen"
  blueGreen:
    # Auto-promoção desabilitada para permitir promoção manual
    autoPromotionEnabled: false
    scaleDownDelaySeconds: 30