# Configuração do Ambiente de Produção
# Este arquivo sobrescreve apenas os valores que diferem do values.yaml padrão

app:
  replicaCount: 10
  springProfile: "prod"
  
  image:
    tag: "main-382384f"

# Configuração do banco de dados para Produção
database:
  clusterName: "saga-chart-prod-postgres"
  host: "saga-chart-prod-postgres-rw"
  name: "sighas_prod"
  password: "best_possible_password_xd"

# Configuração do Job de Migration
migration:
  image:
    tag: "main-382384f"